name: Unit Tests

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run-tests:
    name: Run Unit Tester
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ">=3.12"
    - name: Install Poetry
      run: python3 -m pip install -U poetry
    - name: Install Dependencies
      run: |
         python3 -m poetry lock
         python3 -m poetry install

    # Seriously Github, Secrets cannot be used in reusable workflows, smh
    - name: Run Unit Tests
      env:
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
      run: python3 -m poetry run unit_test -u "$DB_USERNAME" -p "$DB_PASSWORD" -ho "$DB_HOST" -po "$DB_PORT" runSuite
